# Generated by Django 5.0.6 on 2024-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='email',
            field=models.EmailField(default='prueba@gmail.com', max_length=254),
        ),
    ]
